language: go
go:
- 1.13.x
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"
script:
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
deploy:
- provider: script
  script: curl -sL https://git.io/goreleaser | bash
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
after_deploy:
- git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
- bonsai/generate-sha512sum.sh
- bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG"
  tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"
env:
  global:
  - secure: WoK3mio8lyL7CYYBf/X0WRK09mL/1WKttr1Y94kAXr6JdnJmB8SpMP56R3pIaqY9rQhgRHzuAkPx8m4fGLLYBgYCX0n2heyvrPpzAe267scEm7BYWa7DkdmZW5oGwxji71So2efLR3RwFiJDaI9G8hEwyRi9Jkv4MZUy/RIBLpyb2QoNBDmg9cPlBh72j4MzVfsdhxHLvEDhCpvPuqHDW5hANJHqOiaUKnZX2fAoS2zva+TgGlDkhWXRvqlYarQntq1LQ1IrOTQUx6LHT2BCiDz7KXkZiuM8HQ470Uhv6XueeTzpak9kg44hA5NbFmuH8AGJddOXwWevjSvO4T4dah0g8tuU+x5WLTNzfVao+JC3M/V9JAz2/+IQQPl3RngEMGMTZY8ANOCqjpoNBXxw8SB88ZMq42u7N7FretEMyg6LBIkAWyN5jPo0AmTnQYvnoG2vMkWT1e8auyB2mml15ScIL1piDfI4WxPF+JMypXy1bDZ0Jhd31mqUZAtab9e6jPoQD392LtsMzECRHnFxafwKXzbbWxs8bi1BP/DnFS2wYfEki/W1GwT3zIOfqXyl0bQz8pKdVU62YTlqjh6Zs2q+A49vN0RIEfZnscAp1g5s/Iv7cz9GnlreEgXJxUpvoltvzBbksdw16w/QLmloKvbAgVhnUbFsWsS4NJwaMOA=
  - secure: rb+FU7Sn0dUBhI1yldjSAiOxnaBcDkCHQbdKKl4pcs0ljaz5li9bQ+nTavwa6V+G3BF4WyAlPejWjOqGjx69MhaBFlGTtI6q21v2db88zlMx31b2fybEMCqIA3EwuGt4RGLrlQaLxRJoNK9LmQYwdU012p5nitpWCLmZ0/oJ26mRiQL0fi/d5azwKBMJbs8lghmstPnx8uL9dYGnkkZii+aOG6sMXrRx4A21gZufD3VD3N4O4BORiE0l3dnw7DJIt505yvrb6gOEUf2jLQm0uAO/ckvwi9t3O1mbEv7CdertfKC4nWWwWifS6HztFBOp2S9t/TFYKO/X3TPMd6VHzTVaKKtIEjMUUU5od3Pix4NgWu3W8bRDWnTit0CAcrjmWA3UBxsjqGrrxiXgMmUzdFPCxGbmUZTc02cfq/BCdA4o7+QEHFi1TCmMSqT4hr7kLrZaXYEiVg4V16KYYvaRu3YbsdhVbf4jEjv6M9J6ujlP7/1acUAY11LrQBVymw3rVh72A7SP6+Eb7vW3d47tOWrb6WLbODO/8KyUy2J9/xnGk+ghUaADyoFhPrCbROsmlGL3Gf7BG1ESJN9FJly7bz+DcZHEyxvZYAGVqXt52zjsEGwnYFeYZ9NA3xab5mtZ7AQwDOfep2/X3PrIHfvEcVD9VReeRgKGPSjYiSho7FI=
