language: go
go:
- 1.13.x
install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
before_script:
- echo "REPO $TRAVIS_REPO_SLUG TAG ${TRAVIS_TAG}"
script:
- go test -v -covermode=count -coverprofile=coverage.out
- "$HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken
  $COVERALLS_TOKEN"
deploy:
- provider: script
  script: curl -sL https://git.io/goreleaser | bash
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_OS_NAME = linux"
after_deploy:
- git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai
- bonsai/generate-sha512sum.sh
- bonsai/github-release-upload.sh github_api_token=$GITHUB_TOKEN repo_slug="$TRAVIS_REPO_SLUG"
  tag="${TRAVIS_TAG}" filename="dist/$(cat dist/sha512_file)"
env:
  global:
    secure: Yv/31g72WOJPlZAULxBYBAMI3fYN/7ElNhRN3gExbNEgwxaR5t6WKeaG2R6KSsRRk62R7eYgc9GcV54GBq55Yb3z//D1La2Nx0BH5r071NkmyXslXkpdAcQ7etQ3/aSfvHyQbTdQAyhaUlZla/vw7cMT1FJ4NsQIr3pPx4GKGRDN6y/5AsqzDuGnv5uyh4IFAN6/UOk7V0V8JnWdofAC+J0BXSQL1UwrJGCGa+bx0OJPh3geGVl9T9Fal3kxvMmrf5CWQ8M/An0A1iWRuhvDCmn39eA74KBQ6pNfNSt+b3zBcyf8qxlj2oDTNdsQTMiGzpD1Kak92/hKp4G98xZpVyyRlDs/v3lPVCtboe1XLzsaoFGZX0CpPwZlP32VL+z7RfGtIuNXhvr/1CswQJ8Ff+U15W9zz7qbwaDaJeYRhbTBS2wmWWvyfDUHKXhCQJyd98jZvM/X0qAB7MkKOWz9kNv4cggDVVuwSR1uU12iFbCLmbeON3muXsKB/izftTfos6Z16k2gxHsDW63WLYxAjBXKQRI6S94uANxELy1/33B8nGw87pVrBCbxIMbSzwxP7P1jUZo/dmsagLp19KYZ7c6z9Dl4hFD+0xFH1sXVrGlMMt2tWhdCIWK8oX8pA1y1mI6TremWJyYTg1+rep2WnCOwxPH3EsySc0qMQTBAZOc=
